language: node_js
node_js:
- '0.12'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: tYHe+VokmHad9tHllyrT/LNDCeAKFwr+enL6PAHgH/xKbQhm6RFcrgX7qVHznlu1IpX6/LjX0ORyU/+JuxZWtBYhznPyqZ33g3jxj84by2taHlmsU0QXhgIfzin7V+ET/HiFJzSP+H2jLePcZ737c1D89A+ZoRJidYippD6PO24=
  app: heroku-badge
  on:
    repo: welcoMattic/heroku-badge
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
